FROM node:13.13.0-stretch

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV production

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm ci
RUN npm install react-scripts@3.4.0 -g --silent

# add app
COPY . /app

# start app
CMD ["npm", "start"]