export const FETCH_PARAMS_REQUEST = 'FETCH_PARAMS_REQUEST';
export const FETCH_PARAMS_SUCCESS = 'FETCH_PARAMS_SUCCESS';
export const FETCH_PARAMS_FAILURE = 'FETCH_PARAMS_FAILURE';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';
