export const FETCH_PARAMS_REQUEST = 'FETCH_PARAMS_REQUEST';
export const FETCH_PARAMS_SUCCESS = 'FETCH_PARAMS_SUCCESS';
export const FETCH_PARAMS_FAILURE = 'FETCH_PARAMS_FAILURE';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';

export const UPDATE_STEP_PARAMS = 'UPDATE_STEP_PARAMS';
export const UPDATE_STEP_PLOT = 'UPDATE_STEP_PLOT';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_PLOT_REQUEST = 'FETCH_PLOT_REQUEST';
export const FETCH_PLOT_SUCCESS = 'FETCH_PLOT_SUCCESS';
export const FETCH_PLOT_FAILURE = 'FETCH_PLOT_FAILURE';
export const ACTIVATE_PLOT_UPDATE = 'ACTIVATE_PLOT_UPDATE';
export const DEACTIVATE_PLOT_UPDATE = 'DEACTIVATE_PLOT_UPDATE';

export const UPDATE_HYPER = 'UPDATE_HYPER';

export const FETCH_STEP_REQUEST = 'FETCH_STEP_REQUEST';
export const FETCH_STEP_SUCCESS = 'FETCH_STEP_SUCCESS';
export const FETCH_STEP_FAILURE = 'FETCH_STEP_FAILURE';
export const TOGGLE_OPTIMIZE = 'TOGGLE_OPTIMIZE';
export const SET_AVAILABLE_ITERATIONS = 'SET_AVAILABLE_ITERATIONS';

